mqtt proxy

The caller subscribes to a channel.

mqtt proxy is responsible for:

add the Client to the Subscriptions map
subscribe to the server topic
register a listener for incoming traffic
return the Client to the caller, so that he may unsubscribe at any point in time.

** new architecture
The Subscription class represents the clients to the proxy.
A Subscription instance is responsible for holding:

1. listeners that should be invoked when a message is received.
2. publish actions that are to be executed when the subscription is online

** publish
is there a subscription?
no -> create one
* publish
Try and create a new subscription.
The creation of a new subscription is asynchronous.
caller returns
Creation of a new subscription instance.
* Subscription class
Buffer jobs to run until some condition is met.
it has a subscription to establish.
It needs to publish messages.
It needs to receive messages and deliver them to clients.

At any point in time, a subscription may be:

1. In the process of establishing a connection.
2. Publishing a message
3. Delivering a message
4. Admitting new clients.
